### ISSUE TITLE
Sketchpack support?

### ISSUE THREAD

**Issue by Arkkimaagi** [exevil/Keys-For-Sketch#10]
Sketchpacks makes installing sketch plugins quite easy https://github.com/apps/sketchpacks-relay

Could you maybe consider adding support for it?

**Comment by exevil** [comment]
Hey and thanks for the feedback.

Yeah, most likely I'll add Sketchpacks support in the near future.

Best,

**Comment by exevil** [comment]
Done: https://sketchpacks.com/exevil/Keys-For-Sketch
