### ISSUE TITLE
Sketch blacking out ares of interface

### ISSUE THREAD

**Issue by acanderson23** [exevil/Keys-For-Sketch#12]
When I go to the Keys preferences tab, it freezes that window and blacks out the content area below. It also is causing sketch to freeze with blackouts, but it won't crash.

![screen shot 2017-09-06 at 10 19 20 am](https://user-images.githubusercontent.com/31704798/30125526-818a5ce2-92ed-11e7-8f96-c6d49670c444.png)

![screen shot 2017-09-06 at 10 28 34 am](https://user-images.githubusercontent.com/31704798/30125702-2823dd30-92ee-11e7-9c7b-9b568d395fdb.png)

**Comment by exevil** [comment]
@acanderson23: Hey there and thanks for the feedback!

Is it "unfreezes" afterward? Or you need to Force Quit and launch again? If so please provide an error log that Sketch ask you to send after a relaunch.

Thanks!

**Comment by acanderson23** [comment]
I fixed it! It was bad interaction with the Marvel plug-in.

**Comment by exevil** [comment]
Thanks a lot for letting me know. Hopefully, this issue should be fixed in nearest Marvel update when it'll migrate to Swift 4.

Cheers!
