### ISSUE TITLE
Don't see the plugin

### ISSUE THREAD

**Issue by TThrane** [exevil/Keys-For-Sketch#14]
Hi...
Just installed this plugin and restarted Sketch, but I don't see it?

<img width="357" alt="plugins_and_menubar" src="https://user-images.githubusercontent.com/20690222/30151191-cbefe60a-93ae-11e7-843a-e8af46a4f2ae.png">

**Comment by exevil** [comment]
Hey There!

Just open Sketch Preferences via `Cmd+,` or `Sketch -> Preferences...` menu. ;)

Cheers!

**Comment by TThrane** [comment]
Thanks!
