### ISSUE TITLE
Conflict resolution doesn't work while Search is used

### ISSUE THREAD

**Issue by RaphyRaph** [exevil/Keys-For-Sketch#16]
![key bug](https://user-images.githubusercontent.com/3810802/30430436-20f1fa36-9953-11e7-9290-ce786f5dc1d7.gif)

**Comment by exevil** [comment]
Successfully reproduced, thanks a lot.

**Comment by exevil** [comment]
Should be fixed in [the Latest Release](https://github.com/exevil/Keys-For-Sketch/releases/latest). If not, please reopen the issue.

Cheers,
