### ISSUE TITLE
Remove shortcut doesn't work

### ISSUE THREAD

**Issue by RaphyRaph** [exevil/Keys-For-Sketch#17]
I tried to remove the "intersect" shortcut, but it wouldn't let me.

**Comment by exevil** [comment]
Hey there and thanks for the feedback. You mean the default shortcut for "Intersect" command, Alt +Cmd+I? Or you've previously set a custom one and can't restore the default?

**Comment by RaphyRaph** [comment]
I mean the default shortcut for "Intersect" command, Alt +Cmd+I?

**Comment by exevil** [comment]
@RaphyRaph: Please check #7 for the explanation of this behavior.
