### ISSUE TITLE
Crashes sketch when removing and adding keyboard shortcuts

### ISSUE THREAD

**Issue by kashby-motion** [exevil/Keys-For-Sketch#20]
Sketch 46.2
Keys For Sketch 0.8.4
Mac 10.13

It will still remember what key I put it or remove the keyboard shortcut, but will crash sketch every time I try to do either.

**Comment by exevil** [comment]
Hey there and thanks for the feedback!

It's the known issue that actually fixed but the new version should be shipped right after v47 release.

¯\_(ツ)_/¯

**Comment by kashby-motion** [comment]
Awesome. Thank you. By the way, great product, love this plugin.

**Comment by olafchou** [comment]
![jietu20171011-232949](https://user-images.githubusercontent.com/19890798/31451411-a7535808-ae71-11e7-9a1f-42c2c462d19a.jpg)

Even if Sketch 47 ，It still crashes when modify the shortcuts .....  and sketch can't work when I touch the Insert ..... you can see the picture ...

**Comment by exevil** [comment]
Fix is coming guys. Please keep calm.

**Comment by exevil** [comment]
Should be fixed in [the Latest Release](https://github.com/exevil/Keys-For-Sketch/releases/latest). If not, please reopen the issue.

Cheers,
