### ISSUE TITLE
Sketch Beta 48 Compatibility

### ISSUE THREAD

**Issue by round** [exevil/Keys-For-Sketch#23]
Looks like the latest Sketch Beta breaks Keys compatibility on High Sierra (10.13.1 Beta) and causes some instability in the core app itself: https://twitter.com/round/status/925412592205656064.

**Comment by exevil** [comment]
Hey, 

Thanks for the feedback, I'll take a look later. Anyway, the update will come only after the official v48 release. Will update FAQ to clarify this clearly in future.

Cheers,

**Comment by hamishmcneill** [comment]
@exevil 👋 FYI Sketch 48 has now been officially released: https://sketchapp.com/updates/#version-48

**Comment by exevil** [comment]
@hamishmcneill: Hey! Thanks a lot, the 0.8.7 update was just released, enjoy!

**Comment by airpoint** [comment]
v0.8.7 still has some issues though @exevil 

![image](https://user-images.githubusercontent.com/4161138/33662318-45dfcff0-da83-11e7-99eb-e07e63dc2899.png)

**Comment by exevil** [comment]
@airpoint: 0.8.7 is only compatible with the latest Sketch v48. So please make sure that you have the latest version of Sketch too.

**Comment by airpoint** [comment]
@exevil ah! you're right, was checking on a machine where I didn't update 🤦‍♂️ 

0.8.7 is good, cheers :)
