### ISSUE TITLE
0.8.7 not compatible with Sketch v47.x

### ISSUE THREAD

**Issue by giuseppebergman** [exevil/Keys-For-Sketch#25]
Hello, 

Since the 0.8.7 update, the following message pops up at Sketch launch:
<img width="532" alt="capture d ecran 2017-12-07 a 10h11 26" src="https://user-images.githubusercontent.com/11982783/33707228-0cf6a2d6-db37-11e7-9765-8723cb3e6017.png">

Since major Sketch updates are very often full of bugs, user shouldn't be forced to update just to keep the plugin to work… or, at least, it would be useful to advertise the new plugin version is not back-compatible.

Thanks a lot for your work!

**Comment by exevil** [comment]
Hey there!

1. Support of multiple Sketch versions is out of scope for me right now, sorry.
2. You can always roll back to previous Keys version via the [Releases](https://github.com/exevil/Keys-For-Sketch/releases) page.

Please consider that this is my very side free of charge project that I'm not really interested to develop right now, so all I'm going to do is maintain its capability with current release Sketch version to keep it afloat.

Hope you understand.

Cheers,

**Comment by exevil** [comment]
Yeah, maybe so when I'll figure out how to show it in good sight. :)

Thanks for the report.
