### ISSUE TITLE
Keys Error on Sketch 46.2

### ISSUE THREAD

**Issue by aylikostin** [exevil/Keys-For-Sketch#27]
![bitmap](https://user-images.githubusercontent.com/34517500/33951279-3e017338-e037-11e7-9e7a-25c5af0d6f22.png)

Hi!
After updating Keys to latest 0.8.7 version, Sketch (46.2) shows this error every time I try to open it. 
After clicking "OK", Sketch will open normally, but Keys won't work anymore. 

Is there a way to fix this without updating Sketch to newer version?

Thanks.

**Comment by exevil** [comment]
Hey there! 

In short: nope, sorry. Please check out #25 for the details.

Cheers!

**Comment by aylikostin** [comment]
@exevil 

Sorry, didn't saw this one is already answered. I'll rollback to 0.8.6, thanks!

**Comment by exevil** [comment]
No probs, thank you for the feedback though.
