### ISSUE TITLE
Unable to bind a hotkey "Organize Text Styles..."

### ISSUE THREAD

**Issue by okunev** [exevil/Keys-For-Sketch#29]
![unnamed](https://user-images.githubusercontent.com/3657051/38603300-e21f8748-3d75-11e8-8d03-bd4de3fbe028.png)

Can't find using search:

![unnamed-1](https://user-images.githubusercontent.com/3657051/38603309-e5e23c68-3d75-11e8-8d70-a5a3970b7ed9.png)

**Comment by exevil** [comment]
Hey there!

Thanks for the feedback. Should be fixed in [Latest Release](https://github.com/exevil/Keys-For-Sketch/releases/latest)

Cheers!
