### ISSUE TITLE
Unable to bind a hotkey "Show Interface"

### ISSUE THREAD

**Issue by okunev** [exevil/Keys-For-Sketch#30]
When you toggle hiding interface (Cmd + . by default) you can press Cmd + . the second time to show it. Sketch Keys allows to bind Hide interface, but doesn't allow to bind the opposite action.

Here is the command:

<img width="405" alt="1" src="https://user-images.githubusercontent.com/3657051/38683229-a4379d5c-3e75-11e8-8fd5-a10b0f849f2c.png">

Can't find:

<img width="632" alt="2" src="https://user-images.githubusercontent.com/3657051/38683257-afff734e-3e75-11e8-9cb0-3434b4420f02.png">

**Comment by exevil** [comment]
Hey there! 

Thanks for the feedback. Unfortunately, alternate menu items aren't handled by Keys yet. You can find more details regarding this kind of issue in #22.

Closing this issue due to duplication.
