### ISSUE TITLE
Plugin not working in Sketch 50

### ISSUE THREAD

**Issue by bomberstudios** [exevil/Keys-For-Sketch#32]
When launching [Sketch 50b4](http://sketchapp.com/beta/), a warning is shown:

<img width="532" alt="screen shot 2018-05-04 at 14 31 29" src="https://user-images.githubusercontent.com/3832/39628025-ffd22162-4fa7-11e8-89ff-f92b60eefbd1.png">

and the plugin is not loaded. Would be nice to fix that before Sketch 50 is shipped (which will happen *really* soon)

Thanks in advance!

**Comment by exevil** [comment]
@bomberstudios: Hey Ale!

Thanks for the feedback. The [latest release](https://github.com/exevil/Keys-For-Sketch/releases/latest) should properly work with v50.

Cheers!

**Comment by bomberstudios** [comment]
Awesome!
