### ISSUE TITLE
Text edit lag when i enable this plugin.

### ISSUE THREAD

**Issue by Nat30** [exevil/Keys-For-Sketch#6]
Hi, sorry to trouble you again.

The text edit will lag after i installed this plugin. But it will be smooth after i disable the plugin and restart Sketch. Sketch version is 46.2.

Here is the video files. You can see the details via the video.

[video.zip](https://github.com/exevil/Keys-For-Sketch/files/1229949/video.zip)

**Comment by exevil** [comment]
@Nat30: Hey Nat! Thanks a lot. Looks like I found the reason. Will try to release an update shortly.

**Comment by exevil** [comment]
@Nat30: Should be fixed now. Thanks for the report! 🙏
